version: '2'
services:
   instagram-api:
     build:
       context: .
     image: instagram-api
     container_name: php-instagram-server
     restart: always
     ports:
       - "8000:80"

networks:
 default:
   external:
     name: mynet